# Generated by egg v0.0.1

# ── Go Builder ──────────────────────────────────────────────────────────────
FROM golang:latest AS go_builder
WORKDIR /usr/src

# Install goose (migration runner) and sqlc (code generator)
RUN CGO_ENABLED=0 go install github.com/pressly/goose/v3/cmd/goose@latest && \
    go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest

# Download deps first for better layer caching
COPY go.mod go.sum ./
RUN go mod download

# Copy source, generate SQLC repository code, then build
COPY . .
RUN sqlc generate
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o __EGG_APP_NAME__ .

# ── Final Image ─────────────────────────────────────────────────────────────
FROM alpine:latest AS app

RUN apk add --no-cache curl netcat-openbsd

# Binaries
COPY --from=go_builder /go/bin/goose        /usr/local/bin/goose
COPY --from=go_builder /usr/src/__EGG_APP_NAME__ /app/__EGG_APP_NAME__

# Runtime assets (migrations live here, needed by goose at runtime)
COPY --from=go_builder /usr/src/db          /app/db
COPY --from=go_builder /usr/src/assets      /app/assets
COPY --from=go_builder /usr/src/web/dist    /app/web/dist

# Entrypoint
COPY docker/entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh /app/__EGG_APP_NAME__

# Symlink banner for convenience
RUN ln -sf /app/assets/svgs/banner-logo.svg /app/banner.svg

ENV PATH="/app:/usr/local/bin:${PATH}"
EXPOSE __EGG_PORT__
WORKDIR /app

ENTRYPOINT ["/app/entrypoint.sh"]
