/* Generated by egg v0.0.1

Copyright © __EGG_YEAR__ __EGG_AUTHOR__

This is made by the egg framework
*/
package main

import (
    _ "__EGG_NAMESPACE__/docs"
	"__EGG_NAMESPACE__/cmd"
)

// @Title __EGG_APP_NAME__ 
// @Schemes http
// @Version 0.0.1
// @Description This is the swagger page for the Project __EGG_APP_NAME__ generated with Egg-go. use this to test your database connection
// @Contact.name __EGG_AUTHOR__ 
// @Contact.url https://__EGG_NAMESPACE__
// @License.name __EGG_LICENSE__
// @BasePath /api
func main() {
	cmd.Execute()
}
