/* Generated by egg v0.0.1 */

package controllers

import (
	"context"

	"__EGG_NAMESPACE__/cmd/configuration"
	"__EGG_NAMESPACE__/middlewares/configs"
	"__EGG_NAMESPACE__/services"
	"github.com/jackc/pgx/v5/pgxpool"
	echojwt "github.com/labstack/echo-jwt/v4"
	"github.com/labstack/echo/v4"
)


type Controller interface {
	Attatch(e *echo.Echo, middlewares ...echo.MiddlewareFunc)
	ControllerName() string
}

func createControllerParams(config *configuration.Configuration) (*services.Registrar, error) {
	ctx := context.Background()
	db, err := pgxpool.New(ctx, config.Database.URL)
	if err != nil {
		return nil, err
	}

	redisService := services.CreateRedisService(ctx, config)

	return &services.Registrar{
		Config:           config,
		AuthService:      services.CreateAuthService(ctx, db, config),
		MinioService:     services.CreateMinioService(ctx, config),
		RedisService:     redisService,
		UserService:      services.CreateUserService(ctx, db),
		ValidatorService: &services.ValidatorService{},
	}, nil
}

func AttatchControllers(e *echo.Echo, config *configuration.Configuration, conts ...Controller) {
	// configure middlewares here right now it is just an authentication
	for _, v := range conts {
		v.Attatch(e, echojwt.WithConfig(configs.AuthMiddlewareConfig(config)))
	}
}
