/* Generated by egg v0.0.1 */

package services

import (
	"context"

	"__EGG_NAMESPACE__/cmd/configuration"
	"__EGG_NAMESPACE__/db/repository"

	"github.com/coreos/go-oidc/v3/oidc"
	"golang.org/x/oauth2"
)

// AuthService provides authentication services, including creating and checking toknnntttnnens.
type AuthService struct {
	ctx      context.Context
	provider *oidc.Provider
	oathc    oauth2.Config
}


// Returns a refrence to a new UserService to be used in the controller
func CreateAuthService(
	ctx context.Context, 
	config   *configuration.Configuration,
) *AuthService {
	provider, err := oidc.NewProvider(
		ctx,
		"https://"+config.Server.Auth0.Domain+"/",
	)
	if err != nil {
		panic(err)
	}
	oathc := oauth2.Config{
		ClientID:     config.Server.Auth0.ClientID,
		ClientSecret: config.Server.Auth0.ClientSecret,
		RedirectURL:  config.Server.Auth0.Call,
		Endpoint:     provider.Endpoint(),
		Scopes:       []string{oidc.ScopeOpenID, "profile", "email"},

	}
	if err != nil {
		panic(err)
	}
	return &AuthService{
		ctx,
		provider,
		oathc,
	}
}


