/* Generated by egg v0.0.1 */

package services

import (
	"github.com/golang-jwt/jwt/v5"
	"github.com/google/uuid"
)

// CustomJwt holds claims extracted from an Auth0 JWT access token.
//
// Auth0-issued fields (Sub, Email, Picture) are populated automatically by
// the OIDC verifier middleware.  Application-specific fields (UserId, User,
// IsAdmin, ProfilePic) must be populated by looking up the user in your
// database using Sub as the external identity key — see AuthService for the
// recommended pattern.
type CustomJwt struct {
	// Auth0-issued claims
	Sub     string `json:"sub"`
	Email   string `json:"email"`
	Picture string `json:"picture"`
	Name    string `json:"name"`

	// Application-layer fields — populate in AuthService after a DB lookup.
	UserId     uuid.UUID `json:"-"`
	User       string    `json:"-"`
	IsAdmin    bool      `json:"-"`
	ProfilePic string    `json:"-"`

	jwt.RegisteredClaims
}
