/* Generated by egg v0.0.1 */

package services

import (
	"context"
	"errors"
	"sync"

	"__EGG_NAMESPACE__/db/repository"
)

// MockAuthService provides an in-memory implementation of IAuthService for testing.
type MockAuthService struct {
	ctx   context.Context
	mutex sync.RWMutex

	// Test behavior controls
	ShouldFailCreate    bool
	ShouldFailUpdate    bool
	ShouldFailCheckToken bool
	ShouldFailCallback  bool

	CreateErrorMessage     string
	UpdateErrorMessage     string
	CheckTokenErrorMessage string
	CallbackErrorMessage   string

	// Test data tracking
	CreateCallCount     int
	UpdateCallCount     int
	CheckTokenCallCount int
	CallbackCallCount   int

	LastCreateUser    *repository.User
	LastUpdateUser    repository.User
	LastCheckToken    string
	LastCallbackCode  string

	// Configurable return values for Auth0 flow
	MockLoginURL   string
	MockSignupURL  string
	MockClaims     *CustomJwt
}

// CreateMockAuthService creates a new MockAuthService with default settings.
func CreateMockAuthService(ctx context.Context, pool interface{}) *MockAuthService {
	return &MockAuthService{
		ctx:                    ctx,
		CreateErrorMessage:     "Mock Create failure",
		UpdateErrorMessage:     "Mock Update failure",
		CheckTokenErrorMessage: "Mock CheckToken failure",
		CallbackErrorMessage:   "Mock Callback failure",
		MockLoginURL:           "https://mock-auth0.example.com/authorize?login",
		MockSignupURL:          "https://mock-auth0.example.com/authorize?signup",
		MockClaims: &CustomJwt{
			Sub:   "auth0|mock-user-id",
			Email: "mock@example.com",
			Name:  "Mock User",
		},
	}
}

// Reset clears call tracking and resets failure flags.
func (m *MockAuthService) Reset() {
	m.mutex.Lock()
	defer m.mutex.Unlock()

	m.CreateCallCount = 0
	m.UpdateCallCount = 0
	m.CheckTokenCallCount = 0
	m.CallbackCallCount = 0

	m.LastCreateUser = nil
	m.LastUpdateUser = repository.User{}
	m.LastCheckToken = ""
	m.LastCallbackCode = ""

	m.ShouldFailCreate = false
	m.ShouldFailUpdate = false
	m.ShouldFailCheckToken = false
	m.ShouldFailCallback = false
}

func (m *MockAuthService) LoginURL() string {
	return m.MockLoginURL
}

func (m *MockAuthService) SignupURL() string {
	return m.MockSignupURL
}

func (m *MockAuthService) Callback(ctx context.Context, code string) (*CustomJwt, error) {
	m.mutex.Lock()
	m.CallbackCallCount++
	m.LastCallbackCode = code
	m.mutex.Unlock()

	if m.ShouldFailCallback {
		return nil, errors.New(m.CallbackErrorMessage)
	}
	return m.MockClaims, nil
}

func (m *MockAuthService) Create(user *repository.User) (*string, error) {
	m.mutex.Lock()
	m.CreateCallCount++
	m.LastCreateUser = user
	m.mutex.Unlock()

	if m.ShouldFailCreate {
		return nil, errors.New(m.CreateErrorMessage)
	}
	token := "a============================================================//a"
	return &token, nil
}

func (m *MockAuthService) Update(user repository.User) (*string, error) {
	m.mutex.Lock()
	m.UpdateCallCount++
	m.LastUpdateUser = user
	m.mutex.Unlock()

	if m.ShouldFailUpdate {
		return nil, errors.New(m.UpdateErrorMessage)
	}
	token := "a============================================================//a"
	return &token, nil
}

func (m *MockAuthService) CheckToken(token string) error {
	m.mutex.Lock()
	m.CheckTokenCallCount++
	m.LastCheckToken = token
	m.mutex.Unlock()

	if m.ShouldFailCheckToken {
		return errors.New(m.CheckTokenErrorMessage)
	}
	return nil
}
