/* Generated by egg v0.0.1 */

package services

import (
	"context"
	"errors"
	"fmt"
	"net/mail"
	"regexp"
	"strings"
	"unicode"

	"__EGG_NAMESPACE__/cmd/configuration"
	"__EGG_NAMESPACE__/models/requests"
	"github.com/google/uuid"
	"github.com/labstack/echo/v4"
)

// ValidatorService struct
//
// This is a static struct that is used to validate the request body
type ValidatorService struct{}

func (ValidatorService *ValidatorService) Promote(ctx context.Context, config *configuration.Configuration) *ValidatorService {
	return ValidatorService
}

func validateUsername(username string) bool {
	trimmed := strings.TrimSpace(username)
	if trimmed == "" {
		return false
	}
	pattern := `^[a-zA-Z0-9]+$`
	_, err := regexp.MatchString(pattern, trimmed)
	if err != nil {
		return false
	}
	return true
}

func validatePassword(s string) (sevenOrMore, number, upper, special bool) {
	for _, c := range s {
		switch {
		case unicode.IsNumber(c):
			number = true
		case unicode.IsUpper(c):
			upper = true
		case unicode.IsPunct(c) || unicode.IsSymbol(c):
			special = true
		}
	}
	sevenOrMore = len(s) >= 8
	return
}

// ValidateNewUserRequest
//
// ValidateNewUserRequest validates the Body by using the echo.Context.Bind(requsts.NewUserRequest)
// and the returns the marshalled object
func (ValidatorService ValidatorService) ValidateNewUserRequest(e echo.Context) (*requests.NewUserRequest, error) {
	validRequest := new(requests.NewUserRequest)
	if err := e.Bind(&validRequest); err != nil {
		return nil, errors.New("Invalid request body. Please check your input and try again")
	}

	if !validateUsername(validRequest.Username) {
		return nil, fmt.Errorf("Validation failed (%s) is not a valid username", validRequest.Username)
	}

	_, err := mail.ParseAddress(validRequest.Email)
	if err != nil {
		return nil, fmt.Errorf("Validation failed (%s) is not a valid email address", validRequest.Email)
	}

	sevenOrMore, number, upper, special := validatePassword(validRequest.Password)
	if !(sevenOrMore && number && upper && special) {
		return nil, fmt.Errorf(
			"Validation failed. Seven Or More (%t), Number (%t), Upper (%t), Special (%t)",
			sevenOrMore,
			number,
			upper,
			special)
	}

	return validRequest, nil
}

// ValidateLoginRequest validates the Body by using the echo.Context.Bind(requsts.LoginRequest)
// and the returns then last part
func (ValidatorService ValidatorService) ValidateLoginRequest(e echo.Context) (*requests.LoginRequest, error) {
	validRequest := new(requests.LoginRequest)
	if err := e.Bind(&validRequest); err != nil {
		return nil, err
	}
	if validRequest.Email == "" && validRequest.Username == "" {
		err := errors.New("Email and Username cannot be null")
		return nil, err
	}
	// validRequest.Username can be sql injection, but only validate if username is provided
	if validRequest.Username != "" && !validateUsername(validRequest.Username) {
		return nil, fmt.Errorf("Validation failed (%s) is not a valid username", validRequest.Username)
	}
	if validRequest.Password == "" {
		err := errors.New("You must send a password")
		return nil, err
	}
	sevenOrMore, number, upper, special := validatePassword(validRequest.Password)
	if !(sevenOrMore && number && upper && special) {
		return nil, fmt.Errorf(
			"Validation failed. Seven Or More (%t), Number (%t), Upper (%t), Special (%t)",
			sevenOrMore,
			number,
			upper,
			special)
	}
	return validRequest, nil
}

// Validate LoginFormRequest ()
func (vs ValidatorService) ValidateLoginFormRequest(e echo.Context) (*requests.LoginRequest, error) {
	req := &requests.LoginRequest{
		Username: e.FormValue("username"),
		Email:    e.FormValue("email"),
		Password: e.FormValue("password"),
	}

	if req.Email == "" && req.Username == "" {
		err := errors.New("Email and Username cannot be null")
		return nil, err
	}
	if req.Password == "" {
		err := errors.New("You must send a password")
		return nil, err
	}
	return req, nil
}

func (vs ValidatorService) ValidateUpdateUserCredentialRequest(e echo.Context) (*requests.UpdateCredentialsRequest, error) {
	validRequest := new(requests.UpdateCredentialsRequest)
	if err := e.Bind(&validRequest); err != nil {
		return nil, err
	}
	if validRequest.ID == uuid.Nil {
		err := errors.New("ID cannot be null")
		return nil, err
	}
	if !validateUsername(validRequest.Username) {
		return nil, fmt.Errorf("Validation failed (%s) is not a valid username", validRequest.Username)
	}

	_, err := mail.ParseAddress(validRequest.Email)
	if err != nil {
		return nil, err
	}
	if validRequest.OldPassword == "" {
		// we do not want to change the password
		return validRequest, nil
	} else if validRequest.Password == "" && validRequest.OldPassword != "" {
		return nil, errors.New("You must send a password to change the password")
	} else {
		sevenOrMore, number, upper, special := validatePassword(validRequest.Password)
		if !(sevenOrMore && number && upper && special) {
			return nil, fmt.Errorf(
				"Validation failed. Seven Or More (%t), Number (%t), Upper (%t), Special (%t)",
				sevenOrMore,
				number,
				upper,
				special)
		}
	}
	return validRequest, nil

}


