/* Generated by egg v0.0.1 */

package user_handlers

import (
	"fmt"

	"__EGG_NAMESPACE__/models/handlers"
	"__EGG_NAMESPACE__/models/responses"
	"__EGG_NAMESPACE__/services"
	"github.com/labstack/echo/v4"
)

// CallbackHandler handles the Auth0 OAuth2 callback.
// Auth0 redirects here with a ?code= parameter after the user authenticates.
// The handler exchanges the code for tokens, verifies the ID token, and
// returns the authenticated user's claims as JSON.
type CallbackHandler struct {
	claims *services.CustomJwt
	ctx    echo.Context
	err    error
	code   int
	r      *services.Registrar
}

func NewCallbackHandler(
	ctx echo.Context,
	r *services.Registrar,
) *CallbackHandler {
	return &CallbackHandler{
		ctx:  ctx,
		code: 200,
		r:    r,
	}
}

func CallbackJsonHandler(ctx echo.Context, r *services.Registrar) error {
	return NewCallbackHandler(ctx, r).Handle().JSON()
}

func (h *CallbackHandler) Handle() handlers.IHandler {
	authCode := h.ctx.QueryParam("code")
	if authCode == "" {
		return handlers.Lock(h, 400, fmt.Errorf("missing code parameter in Auth0 callback"))
	}

	var err error
	h.claims, err = h.r.AuthService.Callback(h.ctx.Request().Context(), authCode)
	if err != nil {
		return handlers.Lock(h, 500, err)
	}
	return h
}

func (h *CallbackHandler) JSON() error {
	if h.err != nil {
		return responses.NewLoginResponse().Fail(h.ctx, h.code, h.err)
	}
	return h.ctx.JSON(200, map[string]any{
		"sub":     h.claims.Sub,
		"email":   h.claims.Email,
		"name":    h.claims.Name,
		"picture": h.claims.Picture,
	})
}

func (h *CallbackHandler) SetError(err error) handlers.IHandler {
	h.err = err
	return h
}

func (h *CallbackHandler) SetCode(code int) handlers.IHandler {
	h.code = code
	return h
}

func (h *CallbackHandler) Data() any {
	return h.claims
}

func (h *CallbackHandler) Code() int {
	return h.code
}

func (h *CallbackHandler) Error() error {
	return h.err
}
