/* Generated by egg v0.0.1 */

package user_handlers

import (
	"net/http"

	"__EGG_NAMESPACE__/models/handlers"
	"__EGG_NAMESPACE__/models/responses"
	"__EGG_NAMESPACE__/services"
	"github.com/labstack/echo/v4"
)

// LoginHandler redirects the client to the Auth0 authorization endpoint.
// After successful authentication, Auth0 will redirect back to the callback URL.
type LoginHandler struct {
	redirectURL string
	ctx         echo.Context
	code        int
	err         error
	r           *services.Registrar
}

func NewLoginHandler(
	ctx echo.Context,
	registrar *services.Registrar,
) *LoginHandler {
	return &LoginHandler{
		ctx:  ctx,
		code: http.StatusTemporaryRedirect,
		r:    registrar,
	}
}

func LoginJsonHandler(ctx echo.Context, r *services.Registrar) error {
	return NewLoginHandler(ctx, r).Handle().JSON()
}

func (h *LoginHandler) Handle() handlers.IHandler {
	h.redirectURL = h.r.AuthService.LoginURL()
	return h
}

func (h *LoginHandler) JSON() error {
	if h.err != nil {
		return responses.NewLoginResponse().Fail(h.ctx, h.code, h.err)
	}
	return h.ctx.Redirect(http.StatusTemporaryRedirect, h.redirectURL)
}

func (h *LoginHandler) Data() any {
	return h.redirectURL
}

func (h *LoginHandler) SetCode(code int) handlers.IHandler {
	h.code = code
	return h
}

func (h *LoginHandler) SetError(err error) handlers.IHandler {
	h.err = err
	return h
}

func (h *LoginHandler) Error() error {
	return h.err
}

func (h *LoginHandler) Code() int {
	return h.code
}
