/* Generated by egg v0.0.1 */

package user_handlers

import (
	"fmt"

	"__EGG_NAMESPACE__/db/repository"
	"__EGG_NAMESPACE__/models/handlers"
	"__EGG_NAMESPACE__/models/requests"
	"__EGG_NAMESPACE__/models/responses"
	"__EGG_NAMESPACE__/services"
	"github.com/labstack/echo/v4"
)

type LoginHandler struct {
	authenticated    *repository.User
	token            *string
	ctx              echo.Context
	code             int
	err              error
	r                *services.Registrar
}

func NewLoginHandler(
	ctx echo.Context,
	registrar *services.Registrar,
) *LoginHandler {
	return &LoginHandler{
		ctx:              ctx,
		code:             200,
		authenticated:    nil,
		token:            nil,
		err:              nil,
		r:                registrar,
	}
}

func LoginJsonHandler(ctx echo.Context, r *services.Registrar) error {
	return NewLoginHandler(ctx, r).Handle().JSON()
}

func (h *LoginHandler) Handle() handlers.IHandler {
	request := new(requests.LoginRequest)
	var err error
	if request, err = h.r.ValidatorService.ValidateLoginRequest(h.ctx); err != nil {
		return handlers.Lock(h, 400, err)
	}
	h.authenticated, err = h.r.UserService.Login(request)
	if err != nil {
		return handlers.Lock(h, 401, err)
	}
	if h.authenticated == nil {
		return handlers.Lock(h, 401, fmt.Errorf("invalid credentials"))
	}
	fmt.Println(h.authenticated)
	h.token, err = h.r.AuthService.Update(*h.authenticated)
	if err != nil {
		return handlers.Lock(h, 500, err)
	}
	return h
}

func (h *LoginHandler) JSON() error {
	var jwt string
	if h.token == nil {
		jwt = ""
	} else {
		jwt = *h.token
	}
	if h.err == nil {
		return responses.NewLoginResponse().Successful(h.ctx, h.authenticated, jwt)
	} else {
		return responses.NewLoginResponse().Fail(h.ctx, h.code, h.err)
	}
}

func (h *LoginHandler) Data() any {
	return struct {
		Authenticated *repository.User
		Token         *string
	}{
		Authenticated: h.authenticated,
		Token:         h.token,
	}
}

func (h *LoginHandler) SetCode(code int) handlers.IHandler {
	h.code = code
	return h
}

func (h *LoginHandler) SetError(err error) handlers.IHandler {
	h.err = err
	return h
}

func (h *LoginHandler) Error() error {
	return h.err
}

func (h *LoginHandler) Code() int {
	return h.code
}
