/* Generated by egg v0.0.1 */

package user_handlers

import (
	"fmt"

	"__EGG_NAMESPACE__/db/repository"
	"__EGG_NAMESPACE__/models/handlers"
	"__EGG_NAMESPACE__/models/requests"
	"__EGG_NAMESPACE__/models/responses"
	"__EGG_NAMESPACE__/services"
	"github.com/labstack/echo/v4"
)

type RegisterHandler struct {
	newUser          *repository.User
	token            *string
	ctx              echo.Context
	err              error
	code             int
	r                *services.Registrar
}

func NewRegisterHandler(
	ctx echo.Context,
	r *services.Registrar,
) *RegisterHandler {
	return &RegisterHandler{
		ctx:              ctx,
		code:             200,
		newUser:          nil,
		token:            nil,
		err:              nil,
		r:                r,
	}
}

func RegisterJsonHandler(ctx echo.Context, r *services.Registrar) error {
	return NewRegisterHandler(ctx, r).Handle().JSON()
}

func (h *RegisterHandler) Lock(code int, err error) *RegisterHandler {
	h.code = code
	h.err = fmt.Errorf("%d Error: %s", h.code, err.Error())
	return h
}

func (h *RegisterHandler) Handle() handlers.IHandler{
	var request *requests.NewUserRequest
	var err error

	if request, err = h.r.ValidatorService.ValidateNewUserRequest(h.ctx); err != nil {
		return handlers.Lock(h, 400, err)
	}
	fmt.Println(request)
	if h.newUser, err = h.r.UserService.Create(request); err != nil {
		return handlers.Lock(h, 500, err)
	}
	fmt.Println(h.newUser)
	if h.token, err = h.r.AuthService.Create(h.newUser); err != nil {
		return handlers.Lock(h, 500, err)
	}
	return h
}

func (h *RegisterHandler) JSON() error {
	if h.token == nil {
		h.token = new(string)	
	}
	if h.err != nil {
		return responses.NewLoginResponse().Fail(h.ctx, h.code, h.err)
	} else {
		return responses.NewLoginResponse().Successful(h.ctx, h.newUser, *h.token)
	}
}

func (h *RegisterHandler) SetError(err error) handlers.IHandler {
	h.err = err
	return h
}
func (h *RegisterHandler) SetCode(code int) handlers.IHandler {
	h.code = code
	return h
}

func (h *RegisterHandler) Data() any {
	return struct {
		NewUser *repository.User
		Token   *string
	}{
		NewUser: h.newUser,
		Token:   h.token,
	}
}

func (h *RegisterHandler) Code() int {
	return h.code
}

func (h *RegisterHandler) Error() error {
	return h.err
}
