/* Generated by egg v0.0.1 */

package user_handlers

import (
	"net/http"

	"__EGG_NAMESPACE__/models/handlers"
	"__EGG_NAMESPACE__/models/responses"
	"__EGG_NAMESPACE__/services"
	"github.com/labstack/echo/v4"
)

// RegisterHandler redirects the client to Auth0 with screen_hint=signup so the
// Universal Login page opens the registration form directly.
type RegisterHandler struct {
	redirectURL string
	ctx         echo.Context
	err         error
	code        int
	r           *services.Registrar
}

func NewRegisterHandler(
	ctx echo.Context,
	r *services.Registrar,
) *RegisterHandler {
	return &RegisterHandler{
		ctx:  ctx,
		code: http.StatusTemporaryRedirect,
		r:    r,
	}
}

func RegisterJsonHandler(ctx echo.Context, r *services.Registrar) error {
	return NewRegisterHandler(ctx, r).Handle().JSON()
}

func (h *RegisterHandler) Handle() handlers.IHandler {
	h.redirectURL = h.r.AuthService.SignupURL()
	return h
}

func (h *RegisterHandler) JSON() error {
	if h.err != nil {
		return responses.NewLoginResponse().Fail(h.ctx, h.code, h.err)
	}
	return h.ctx.Redirect(http.StatusTemporaryRedirect, h.redirectURL)
}

func (h *RegisterHandler) SetError(err error) handlers.IHandler {
	h.err = err
	return h
}

func (h *RegisterHandler) SetCode(code int) handlers.IHandler {
	h.code = code
	return h
}

func (h *RegisterHandler) Data() any {
	return h.redirectURL
}

func (h *RegisterHandler) Code() int {
	return h.code
}

func (h *RegisterHandler) Error() error {
	return h.err
}
