/* Generated by egg v0.0.1 */

package user_handlers

import (
	"mime/multipart"

	"__EGG_NAMESPACE__/db/repository"
	"__EGG_NAMESPACE__/models/handlers"
	"__EGG_NAMESPACE__/models/responses"
	"__EGG_NAMESPACE__/services"
	"github.com/golang-jwt/jwt/v5"
	"github.com/labstack/echo/v4"
)

type UploadProfilePictureHandler struct {
	ctx      echo.Context
	err      error
	code     int
	response *repository.User
	registrar *services.Registrar
}

func NewUploadProfilePictureHandler(
	ctx echo.Context,
	registrar *services.Registrar,
) *UploadProfilePictureHandler {
	return &UploadProfilePictureHandler{
		ctx:  ctx,
		err:  nil,
		code: 200,
		registrar: registrar,
	}
}

func UploadProfilePictureJsonHandler(ctx echo.Context, r *services.Registrar) error {
	return NewUploadProfilePictureHandler(ctx, r).Handle().JSON()
}

func (h *UploadProfilePictureHandler) Lock(code int, err error) handlers.IHandler {
	return handlers.Lock(h, code, err)
}

func (h *UploadProfilePictureHandler) SetCode(code int) handlers.IHandler {
	h.code = code
	return h
}

func (h *UploadProfilePictureHandler) Code() int {
	return h.code
}

func (h *UploadProfilePictureHandler) Data() any {
	return h.response
}

func (h *UploadProfilePictureHandler) Error() error {
	return h.err
}

func (h *UploadProfilePictureHandler) SetError(err error) handlers.IHandler {
	h.err = err
	return h
}

func (h *UploadProfilePictureHandler) Handle() handlers.IHandler {
	filename := "" 
	jwt_token := h.ctx.Get("user").(*jwt.Token)
	claims := jwt_token.Claims.(*services.CustomJwt)
	userId := claims.UserId
	err := h.registrar.AuthService.CheckToken(jwt_token.Raw)
	if err != nil {
		return handlers.Lock(h,401, err)
	}
	var file *multipart.FileHeader
	var src multipart.File
	file, err = h.ctx.FormFile("file")
	if err != nil {
		return handlers.Lock(h, 400, err)
	}
	src, err = file.Open()
	if err != nil {
		return handlers.Lock(h, 500, err)
	}
	defer src.Close()
	filename = file.Filename
	err = h.registrar.MinioService.Upload(
		userId,
		filename,
		src,
		file.Size,
		"profile-pic",
	)
	if err != nil {
		return handlers.Lock(h, 500, err)
	}
	h.response, err = h.registrar.UserService.Update(userId, filename)
	if err != nil {
		return handlers.Lock(h, 500, err)
	}
	return h

}

func (h *UploadProfilePictureHandler) JSON() error {
	if h.err != nil {
		return responses.NewUserResponse().Fail(h.ctx, h.code, h.err)
	} else {
		return responses.NewUserResponse().Successful(h.ctx, h.response)
	}
}
