/* Generated by egg v0.0.1
Copyright © __EGG_YEAR__ __EGG_AUTHOR__
License: __EGG_LICENSE__

*/
package cmd

import (
	"bufio"
	"errors"
	"os"
	"os/exec"

	"__EGG_NAMESPACE__/cmd/configuration"
	"github.com/spf13/cobra"
)

// downCmd represents the down command
var downCmd = &cobra.Command{
	Use:   "down",
	Short: " This command uses goose to run down migrations in the `__EGG_MIGRATION_DEST__` folder",
	Long: `
*** Help Text
    this is effectively goose down

*** Command 
**** Default 
--- bash
go build main.go -o __EGG_APP_NAME__
./__EGG_APP_NAME__ db down 
---

**** with -e passed
--- bash
go build main.go -o __EGG_APP_NAME__
./__EGG_APP_NAME__ db down -e really-sick-config
---
`,
	Run: func(cmd *cobra.Command, args []string) {
        config, err := configuration.LoadConfiguration(Environment) 
        if err != nil {
            panic(err)
        }
        if err = Down(config, args); err != nil {
            panic(err)
        }
        print("🥚 Goose Down Successful")
	},
}

func init() {
	rootCmd.AddCommand(downCmd)
}

func Down(configuration *configuration.Configuration, args []string) error {
    os.Setenv("GOOSE_DRIVER", configuration.Database.Migration.Protocol)
    os.Setenv("GOOSE_MIGRATION_DIR", configuration.Database.Migration.Destination)
    if len(args) != 0 {
        return errors.New("len(args) != 0 so the cli does not know what to do.")
    }

    output, err := exec.Command("goose", "down", configuration.Database.Sqlc.SqlOrGo).Output()
    if err != nil {
        return err
    }
    writer := bufio.NewWriter(os.Stdout)
    _, err = writer.Write(output)
    if err != nil {
        return err
    }
    return nil
}
