/* Generated by egg v0.0.1
Copyright © __EGG_YEAR__ __EGG_AUTHOR__
License: __EGG_LICENSE__

*/
package cmd

import (
	"fmt"
	"os"
	"os/exec"

	"__EGG_NAMESPACE__/cmd/configuration"
	"github.com/spf13/cobra"
)

// swagCmd represents the swag command
var swagCmd = &cobra.Command{
	Use:   "swag",
	Short: "A brief description of your command",
	Long: ` A long description of your command`,
	Run: func(cmd *cobra.Command, args []string) {
		if err := swag(); err != nil {
			fmt.Println(err.Error())
			return
		}
	},
}


func init() {
	rootCmd.AddCommand(swagCmd)
}

func swag() error {
	config, err := configuration.LoadConfiguration(Environment)
	if err != nil {
		return err
	}

	// first run swag
	output, err := exec.Command("swag", "init").Output()
	fmt.Printf("%s\n", string(output))
	if err != nil {
		return err
	}

	outputDir := config.Server.Frontend.Api
	fmt.Printf("%s\n", outputDir)
	if _, err = os.Stat(outputDir); os.IsNotExist(err) {
		// create the directory
		fmt.Println("need to create")
		if err := os.Mkdir(outputDir, os.ModePerm); err != nil {
			fmt.Printf("%s\n", err.Error())
			return err
		}
	}

	// now do the open api
	fmt.Println("Scaffolding typescript-fetch api")
	output, err = exec.Command(
		"openapi-generator-cli",
		"generate",
		"-g",
		"typescript-fetch",
		"-o",
		outputDir,
		"-i",
		"docs/swagger.json",
	).Output()
	if err != nil {
		println(err.Error())
		fmt.Printf("%s", output)

		return err
	}
	fmt.Printf("%s", output)

	return nil
}
