/* Generated by egg v0.0.1
Copyright © __EGG_YEAR__ __EGG_AUTHOR__
License: __EGG_LICENSE__

*/
package cmd

import (
	"errors"
	"fmt"
	"os"
	"os/exec"

	"__EGG_NAMESPACE__/cmd/configuration"
	"github.com/spf13/cobra"
)

// upCmd represents the up command
var upCmd = &cobra.Command{
	Use:   "up",
	Short: "This command uses sql to generate the repository code from the `internal/migrations`.",
	Long: `
*** Help Text
This command calls goose migrations under the hood. And by default it uses 
the following environment variables:

--- .env
GOOSE_DRIVER=config.Server.Database.Migration.Protocol
GOOSE_DBSTRING=config.Server.Database.Url
GOOSE_MIGRATION_DIR=config.Server.Database.Migration.Destination
---

this is effectively goose up

*** Command 
**** Default 
--- bash
go build main.go -o __EGG_APP_NAME__ 
__EGG_APP_NAME__ db up 
---

**** with -e passed
@code bash
--- bash
go build main.go -o __EGG_APP_NAME__
__EGG_APP_NAME__ db up -e really-sick-config
---
`,
	Run: func(cmd *cobra.Command, args []string) {
        config, err := configuration.LoadConfiguration(Environment) 
        if err != nil {
            panic(err)
        }
        if err = Up(config, args); err != nil {
            print(err.Error())
			os.Exit(1)
        }
        print("🥚 Goose Up Successful")
	},
}

func init() {
	dbCmd.AddCommand(upCmd)
}

func Up(configuration *configuration.Configuration, args []string) error {
    os.Setenv("GOOSE_DRIVER", configuration.Database.Migration.Protocol)
    os.Setenv("GOOSE_MIGRATION_DIR", configuration.Database.Migration.Destination)
    os.Setenv("GOOSE_DBSTRING", configuration.Database.URL)
    if len(args) != 0 {
        return errors.New("len(args) != 0 so the cli does not know what to do.")
    }

    command := exec.Command("goose", "up", "-v")
    command.Stdout = os.Stdout
    command.Stderr = os.Stderr
    if err := command.Run(); err != nil {
        return fmt.Errorf("goose up failed: %w", err)
    }
    return nil
}

